@Echo Off
Echo ">>>>>>>>>>>>>start-----------------------------------------------------------------------"
Echo "1.>>>.\access-oop\bin\access-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
start "" ".\access-oop\bin\access-oop-mds2index.html.bat"
Echo "2.>>>.\arangodb-oop\bin\arangodb-oop-mds2index.html.bat"
start "" ".\arangodb-oop\bin\arangodb-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "3.>>>.\db2-oop\bin\db2-oop-mds2index.html.bat"
start "" ".\db2-oop\bin\db2-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "4.>>>.\elasticsearch-oop\bin\elasticsearch-oop-mds2index.html.bat"
start "" ".\elasticsearch-oop\bin\elasticsearch-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "5.>>>.\mongodb-oop\bin\mongodb-oop-mds2index.html.bat"
start "" ".\mongodb-oop\bin\mongodb-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "6.>>>.\mysql-oop\bin\mysql-oop-mds2index.html.bat"
start "" ".\mysql-oop\bin\mysql-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "7.>>>.\oracle-oop\bin\oracle-oop-mds2index.html.bat"
start "" ".\oracle-oop\bin\oracle-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "8.>>>.\postgresql-oop\bin\postgresql-oop-mds2index.html.bat"
start "" ".\postgresql-oop\bin\postgresql-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "9.>>>.\redis-oop\bin\redis-oop-mds2index.html.bat"
start "" ".\redis-oop\bin\redis-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "10.>>>.\sqlite-oop\bin\sqlite-oop-mds2index.html.bat"
start "" ".\sqlite-oop\bin\sqlite-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "11.>>>.\sqlserver-oop\bin\sqlserver-oop-mds2index.html.bat"
start "" ".\sqlserver-oop\bin\sqlserver-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Echo "12.>>>.\xml-oop\bin\xml-oop-mds2index.html.bat"
start "" ".\xml-oop\bin\xml-oop-mds2index.html.bat"
Echo "-----------------------------------------------------------------------------------------"
Pause>nul
Exist 